import type { Metadata } from "next";
import { Sriracha } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";

const geistSans = Sriracha({
  weight: "400",
  variable: "--font-sriracha",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <AuthProvider>
        <body
          className={`${geistSans.variable} antialiased`}
        >
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
